version: '3.4'

services:
  posts-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: senhaForte123
      MYSQL_USER: docker
      MYSQL_PASSWORD: senhaForte123
      MYSQL_DATABASE: posts_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    networks:
      - geek-theories-network

  posts-service:
    image: maven:3.8.4-openjdk-17-slim
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://posts-db:3306/posts_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: senhaForte123
      SPRING.FLYWAY.URL: jdbc:mysql://posts-db:3306/posts_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: senhaForte123
    ports:
      - 8000:8000
    volumes:
      - ./posts-service:/app
    working_dir: /app
    command: sh -c "cd /app && mvn spring-boot:run"
    depends_on:
      - posts-db
    user: root
    networks:
      - geek-theories-network

networks:
  geek-theories-network:
    driver: bridge
