server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
spring:
  application:
    name: posts-service
  config:
    import: optional:configserver:http://config-server:8889
  cloud:
    config:
      profile: dev
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://posts-db:3306/posts_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: root
    password: senhaForte123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://posts-db:3306/posts_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    schemas: posts_service
    user: root
    password: senhaForte123